[global]
   workgroup = WORKSHOP
   server string = Enumeration Lab Samba Server
   map to guest = Bad User
   log file = /var/log/samba/log.%m
   max log size = 50
   server role = standalone server
   obey pam restrictions = no
   pam password change = no
   passwd program = /bin/false
   unix password sync = no

[public]
   path = /srv/samba/public
   browseable = yes
   read only = no
   guest ok = yes
   map to guest = Bad User
