[global]
   workgroup = WORKSHOP
   server string = Enumeration Lab Samba Server
   map to guest = Bad User
   server role = standalone server
   log file = /var/log/samba/log.%m
   max log size = 50
   obey pam restrictions = no
   pam password change = no
   passwd program = /bin/false
   unix password sync = no
   guest account = nobody

[public]
   path = /srv/samba/public
   browseable = yes
   read only = yes
   guest ok = yesagentAddress udp:161
sysLocation Docker Enumeration Lab
sysContact nobody https://youtu.be/KrZHPOeOxQQ?si=BE0oTnLRDr23emG6
sysName enumlab-target
rocommunity public
view all included .1 80
